### PR TITLE
Use electron connect

### PR DESCRIPTION
**Pull request by geekytime**
The webpack-hot-loader stuff wasn't working very well in Electron. After trying a few flavors of live-reload that also weren't very happy in Electron, I stumbled upon [electron-connect](https://github.com/Quramy/electron-connect), which, despite the mysterious name, is made for just this purpose.

Now the `start-watch` command is a one-shot-deal. Everything is much cleaner and easier to understand, and it works better.

I also standardized the developer task names a bit, and created a watch for each dev task.

### CODE REVIEW

**Comment by geekytime** [comment]
@H3Chief, do you want to try this on a mac before I merge it?

**Comment by H3Chief** [comment]
I fired it up, and then changed the border color property of the team-button from the green it is to black.  It worked well, and reloaded fined. then I changed it back, and it closed the app.  Here's the log:

screen shot 2015-12-10 at 1 51 45 pm

**Comment by H3Chief** [comment]
I can't repro that first crash... and I had 2 electron process running, so I think it was human error that caused it.

:+1:

**Comment by geekytime** [comment]
Well,I have seen a few more crashes, but they're not prevalent enough for me to abandon this, yet. It still refreshes better than hot-loader or live-reload did for me.

**Pull request merged**
