### PR TITLE
Reactify team webview

### PR DESCRIPTION
**Pull request by geekytime**
Create a React component to wrap the team webview. It handles events from the webview and delegates notification events to the new notification api.

This organizational work is all in preparation for adding additional webviews for multiple teams. We're getting closer!

@H3Chief - I'll wait a little bit to merge this in case you want to test the notifications part on a mac.

I think right now you have to be in another channel for notifications to appear. We may have to add logic to scrape the title from the webview window, as I think that's how MM is alerting the user of unreads in the open channel, now.

### CODE REVIEW

**Comment by geekytime** [comment]
Ooh! I just realized we could also monkey-patch the notification API itself. We hijack the calls to show notifications, and then pass them through to the real API. That'd be the way to do it, because then their Mattermost settings would still work.

**Comment by H3Chief** [comment]
ok, so do you want me to wait on my review?

**Comment by geekytime** [comment]
No. I'll do that in the next branch.

And the Notifications API triggers events. It should be nice and easy. :smile_cat:

**Comment by H3Chief** [comment]
What are you using to test notifications?

**Comment by H3Chief** [comment]
The vagrant box included I'm guessing? Or are you loading a legit mattermost server?

**Comment by geekytime** [comment]
I was hitting a real one. You need people to post things so you get notifications. :smirk:

**Comment by H3Chief** [comment]
So in other words... you're stalking and/or antagonizing someone in order to test. Got it. :tongue:

**Pull request merged**
