### PR TITLE
Multi team notifications

### PR DESCRIPTION
**Pull request by geekytime**
Adds little badges to each team for unreads and mentions, and provides a better "selected" icon.

A few things that don't work, yet, and are going to be difficult to get working:

- Notifications for channels that are open, but webviews that are unfocused
- Themes. We could try to guess light/dark from inside the webview and provide two themes for that, but custom themes are probably out, unless Mattermost has an API to fetch colors

### CODE REVIEW

**Comment by geekytime** [comment]
Actually, now that I think about it, I want to clean up the colors and see if I can get them to match the theme. I'm going to try to grab the colors from the appropriate elements in the webview.

**Comment by geekytime** [comment]
> I'm going to try to grab the colors from the appropriate elements in the webview.

Never mind. I'll do this in the next branch.

**Comment by H3Chief** [comment]
i thought we were going to hold off on merging stuff into our master branch?

**Comment by geekytime** [comment]
I thought we were using Github flow within our forked repo.

**Comment by geekytime** [comment]
That's why I've been opening and merging PRs.

Then we can submit a big PR back to upstream when we're closer to being feature-complete.

**Pull request merged**
